server:
  port: 7090
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: ITA
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:itadb
    username: admin
    password: admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.sss
    time-zone: America/New_York
  h2:
    console:
      enabled: true
      path: /db
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: none


app-props:
  map_center_lng: -76.65794130637283
  map_center_lat: 38.39741362559147
